// flow-typed signature: ad4f56ca1dd756ec8a6d6f76a83a3ec7
// flow-typed version: <<STUB>>/react-addons-shallow-compare_v^15.6.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-shallow-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-shallow-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-addons-shallow-compare/react-addons-shallow-compare' {
  declare module.exports: any;
}

declare module 'react-addons-shallow-compare/react-addons-shallow-compare.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-addons-shallow-compare/index' {
  declare module.exports: $Exports<'react-addons-shallow-compare'>;
}
declare module 'react-addons-shallow-compare/index.js' {
  declare module.exports: $Exports<'react-addons-shallow-compare'>;
}
declare module 'react-addons-shallow-compare/react-addons-shallow-compare.js' {
  declare module.exports: $Exports<'react-addons-shallow-compare/react-addons-shallow-compare'>;
}
declare module 'react-addons-shallow-compare/react-addons-shallow-compare.min.js' {
  declare module.exports: $Exports<'react-addons-shallow-compare/react-addons-shallow-compare.min'>;
}
